// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

#include "/home/mateusz/repos/test_sdk/build/_deps/pico_sdk-src/src/boards/include/boards/pico.h"
#include "/home/mateusz/repos/test_sdk/build/_deps/pico_sdk-src/src/rp2_common/cmsis/include/cmsis/rename_exceptions.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:
